version: "3.9"

services:
  backend:
    build: ./backend
    container_name: eduguard-backend
    env_file: .env
    volumes:
      - backend-data:/app/data
      - backend-versions:/app/model/versions
    networks:
      - eduguard
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: eduguard-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - eduguard
    restart: unless-stopped

volumes:
  backend-data:
  backend-versions:

networks:
  eduguard:
    driver: bridge
